# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.4

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/IndentationWidth:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Include:
    - "app/**/*"
    - "config/**/*"
    - "lib/**/*"
    - "spec/**/*"
    - "Gemfile"

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never