name: CI

on:
  push:
    branches: ["**"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract Node.js version from mise.toml
        id: node-version
        run: |
          VERSION=$(grep -oP 'node = "\K[^"]+' mise.toml)
          echo "node-version=$VERSION" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.node-version }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Run check script
        run: bun run check

      - name: Run build script
        run: bun run build
  build:
    needs: check

    if: contains(github.ref, 'master')

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build docker image
      run: docker build -t atw:latest .

    - name: Save docker image as tarball
      run: docker save atw:latest | gzip > atw.tar.gz

    - name: Copy docker image tarball to production
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: atw.tar.gz
        target: ${{ secrets.TARGET_PATH }}
