name: CI
on: [push]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Extract Node version
        id: node-version
        run: |
          NODE_VERSION=$(grep 'node =' mise.toml | cut -d '"' -f 2)
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.node-version.outputs.node_version }}
          
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: bun install
        
      - name: Run checks
        run: bun run check
        
      - name: Build project
        run: bun run build
